import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/Sidebar'

const nunito = Nunito()

export const metadata: Metadata = {
  title: 'BookWise',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <div className="grid-cols-app grid min-h-screen bg-gray-800 p-5">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
